services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: OlexandrRya/link-generator:latest
    container_name: app
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on: []